namespace DarenaHealth.Models.HR.Enums;

/// <summary>
/// Different types of observations
/// </summary>
public enum ObservationType
{
    /// <summary>
    /// Observation is a risk category assessment
    /// </summary>
    RiskCategoryAssessment = 0,

    /// <summary>
    /// Observations generated by physical exam findings including direct observations made by a clinician and use of simple instruments and the result of simple maneuvers performed directly on the patient's body.
    /// </summary>
    PhysicalExam = 1,

    /// <summary>
    /// The results of observations generated by laboratories. Laboratory results are typically generated by laboratories providing analytic services in areas such as chemistry, hematology, serology, histology, cytology, anatomic pathology (including digital pathology), microbiology, and/or virology. These observations are based on analysis of specimens obtained from the patient and submitted to the laboratory.
    /// </summary>
    LabTest = 2,

    /// <summary>
    /// Observation is a diagnostic study
    /// </summary>
    DiagnosticStudy = 3,

    /// <summary>
    /// Observation is a functional status
    /// </summary>
    FunctionalStatus = 4,

    /// <summary>
    /// Observation is a patient characteristic
    /// </summary>
    PatientCharacteristic = 5,

    /// <summary>
    /// Social History Observations define the patient's occupational, personal (e.g., lifestyle), social, familial, and environmental history and health risk factors that may impact the patient's health.
    /// </summary>
    SocialHistory = 6,

    /// <summary>
    /// Clinical observations measure the body's basic functions such as blood pressure, heart rate, respiratory rate, height, weight, body mass index, head circumference, pulse oximetry, temperature, and body surface area.
    /// </summary>
    VitalSigns = 7,

    /// <summary>
    /// Observations generated by imaging. The scope includes observations regarding plain x-ray, ultrasound, CT, MRI, angiography, echocardiography, and nuclear medicine.
    /// </summary>
    Imaging = 8,

    /// <summary>
    /// Observations generated by other procedures. This category includes observations resulting from interventional and non-interventional procedures excluding laboratory and imaging (e.g., cardiology catheterization, endoscopy, electrodiagnostics, etc.). Procedure results are typically generated by a clinician to provide more granular information about component observations made during a procedure. An example would be when a gastroenterologist reports the size of a polyp observed during a colonoscopy.
    /// </summary>
    Procedure = 9,

    /// <summary>
    /// Assessment tool/survey instrument observations (e.g., Apgar Scores, Montreal Cognitive Assessment (MoCA)).
    /// </summary>
    Survey = 10,

    /// <summary>
    /// Observations generated by non-interventional treatment protocols (e.g. occupational, physical, radiation, nutritional and medication therapy)
    /// </summary>
    Therapy = 11,

    /// <summary>
    /// Observations that measure or record any bodily activity that enhances or maintains physical fitness and overall health and wellness. Not under direct supervision of practitioner such as a physical therapist. (e.g., laps swum, steps, sleep data)
    /// </summary>
    Activity = 12,
}